---
- name: Configure vlans
  hosts: switches
  gather_facts: no
  vars:
    vlans:
      - name: vlan10
        vlan_id: 10
      - name: vlan20
        vlan_id: 20
      - name: vlan30
        vlan_id: 30


  tasks:
    - name: Create vlans
      junipernetworks.junos.junos_vlans:
        config:
          - name: "{{ item.name }}"
            vlan_id: "{{ item.vlan_id }}"
        state: merged
      loop: "{{ vlans }}"
      when: item.vlan_id is defined
        
  tasks:
    - name: Get vlans
      junipernetworks.junos.junos_command:
        commands: show vlans
      register: output

    - name: Print vlans
      debug:
        var: output.stdout_lines
