---
- name: Configure vlans
  hosts: switches
  gather_facts: no
  vars:
    vlans:
      - name: vlan10
        vlan_id: 10
      - name: vlan20
        vlan_id: 20
      - name: vlan30
        vlan_id: 30

  tasks:
    - name: Enter configuration mode
      ansible.builtin.shell: "configure"
      register: enter_config_mode
      ignore_errors: true

    - name: Create vlans
      ansible.builtin.shell: "cli -c 'set vlans {{ item.name }} vlan-id {{ item.vlan_id }}'"
      loop: "{{ vlans }}"
      when: item.vlan_id is defined
        

    - name: Get vlans
      ansible.builtin.shell: "cli -c 'show vlans'"
      register: output

    - name: Print vlans
      debug:
        var: output.stdout_lines